With the new python 3 and the new csvkit, the inputs to csvcut need to be modified like this to give the expected output (#72)
* With the new python 3 and the new csvkit, the inputs to csvcut need to be modified like this to give the expected output

* Skip update step to avoid errors

Currently failing with:

Error: msodbcsql17 conflicts with unixODBC-utf16-2.3.1-1.x86_64
Error: msodbcsql conflicts with unixODBC-utf16-2.3.1-1.x86_64
Error: unixODBC-utf16 conflicts with unixODBC-2.3.1-14.amzn2.x86_64

* Fix new line character error

```
Error message:  new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

* fix pip running as root warning

Co-authored-by: Duck <duckalini@users.noreply.github.com>